spring:
  application:
    name: verleih-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true