spring:
  application:
    name: verleih-service
  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

opentracing:
  jaeger:
    service-name: verleih-service
    enabled: true
    udp-sender:
      host: localhost
