spring:
  application:
    name: verleih-service
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

#opentracing:
#  jaeger:
#    service-name: OpenTracingAppA
#    enabled: true
#    udp-sender:
#      host: localhost
